org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.219
loader_version_range=[1,)
epicfight_version=21.16.3-mc1.21.1-neoforge

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

epicfight_version_range=[21.16.1,)

mod_id=p1nero_bow
mod_name=P1nero's Epic Fight Bow
mod_license=All Rights Reserved
mod_version=21.16.1.0-neoforge
mod_group_id=com.p1nero.epicfightbow
mod_authors=P1nero, Merlin204, yzlgdxw
mod_description=Add bow anim to Epic Fight
